export const SET_THEME_MUTATION = 'SET_THEME_MUTATION'
export const OPEN_MODAL_MUTATION = 'OPEN_MODAL_MUTATION'
export const CLOSE_MODAL_MUTATION = 'CLOSE_MODAL_MUTATION'
export const SET_TOKEN_MUTATION = 'SET_TOKEN_MUTATION'

// Tweets
export const ADD_TWEET_MUTATION = 'ADD_TWEET_MUTATION'

// User
export const SET_USER_MUTATION = 'SET_USER_MUTATION'
