export const SET_THEME_MUTATION = 'SET_THEME_MUTATION'
export const OPEN_MODAL_MUTATION = 'OPEN_MODAL_MUTATION'
export const CLOSE_MODAL_MUTATION = 'CLOSE_MODAL_MUTATION'
export const SET_TOKEN_MUTATION = 'SET_TOKEN_MUTATION'

// Tweets
export const ADD_TWEET_MUTATION = 'ADD_TWEET_MUTATION'
export const TWEET_INDEX_MUTATION = 'TWEET_INDEX_MUTATION'

// User
export const SET_USER_MUTATION = 'SET_USER_MUTATION'
export const SET_FOLLOW_USER_MUTATION = 'SET_FOLLOW_USER_MUTATION'
export const SET_UNFOLLOW_USER_MUTATION = 'SET_UNFOLLOW_USER_MUTATION'

// Profile
export const SET_PROFILE_MUTATION = 'SET_PROFILE_MUTATION'
