export const SET_THEME_MUTATION = 'SET_THEME_MUTATION'
export const OPEN_MODAL_MUTATION = 'OPEN_MODAL_MUTATION'
export const CLOSE_MODAL_MUTATION = 'CLOSE_MODAL_MUTATION'
export const SET_TOKEN_MUTATION = 'SET_TOKEN_MUTATION'
